name: Comment on Commit

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Request
        uses: peter-evans/commit-comment@v1
        with:
          body: '@coderabbitai review'